# Example workflow files that other repositories can copy and use

# =============================================================================
# EXAMPLE 1: Simple usage with SonarQube integration
# =============================================================================
# Copy this workflow to: .github/workflows/security-report.yml

name: Generate Security Report

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  security-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate SonarQube Sunshine Report
      uses: mathiasconradt/sonarqube-sunshine/.github/actions/sonarqube-sunshine@main
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
        component-key: ${{ secrets.COMPONENT_KEY }}
        branch: ${{ secrets.BRANCH }}
        enrich-cves: true
        deploy-to-pages: true

    - name: Upload Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: security-report
        path: report.html

# =============================================================================
# EXAMPLE 2: File-based input (for repos with SBOM files)
# =============================================================================

name: Generate Security Report from SBOM

on:
  push:
    branches: [ main ]

jobs:
  security-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate Report from SBOM
      uses: mathiasconradt/sonarqube-sunshine/.github/actions/sonarqube-sunshine@main
      with:
        input-file: 'path/to/your/sbom.json'  # Adjust path as needed
        output-file: 'security-report.html'
        enrich-cves: true
        deploy-to-pages: true
        pages-url: 'https://your-custom-domain.com/reports/security-report.html'

# =============================================================================
# EXAMPLE 3: Manual workflow with all options
# =============================================================================

name: Security Report (Manual)

on:
  workflow_dispatch:
    inputs:
      sonar_host_url:
        description: 'SonarQube Host URL'
        required: false
        type: string
      component_key:
        description: 'Component Key'
        required: false
        type: string
      branch:
        description: 'Branch Name'
        required: false
        type: string
      input_file:
        description: 'Input SBOM File Path'
        required: false
        type: string
      enrich_cves:
        description: 'Enrich CVEs'
        required: false
        type: boolean
        default: true

jobs:
  security-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate Custom Report
      uses: mathiasconradt/sonarqube-sunshine/.github/actions/sonarqube-sunshine@main
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        sonar-host-url: ${{ github.event.inputs.sonar_host_url }}
        component-key: ${{ github.event.inputs.component_key }}
        branch: ${{ github.event.inputs.branch }}
        input-file: ${{ github.event.inputs.input_file }}
        enrich-cves: ${{ github.event.inputs.enrich_cves }}
        deploy-to-pages: true
